/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchingImport } from './routes/searching'
import { Route as SearchImport } from './routes/search'
import { Route as AboutImport } from './routes/about'
import { Route as Layout1Import } from './routes/_layout1'
import { Route as PokemonIndexImport } from './routes/pokemon/index'
import { Route as UserUsernameImport } from './routes/user.$username'
import { Route as PokemonIdImport } from './routes/pokemon/$id'
import { Route as hiddenFolderFirstLevelImport } from './routes/(hidden-folder)/first-level'
import { Route as Layout1UserRouteImport } from './routes/_layout1/user/route'
import { Route as OneTwoThreeImport } from './routes/one.two.three'
import { Route as FooBarBazImport } from './routes/foo/bar/baz'
import { Route as hiddenFolderLayoutsVisibleLayoutImport } from './routes/(hidden-folder)/layouts/visibleLayout'
import { Route as hiddenFolderLayoutsHiddenLayoutImport } from './routes/(hidden-folder)/layouts/_hiddenLayout'
import { Route as hiddenFolderLayoutsVisibleLayoutFooImport } from './routes/(hidden-folder)/layouts/visibleLayout/foo'
import { Route as hiddenFolderLayoutsVisibleLayoutBarImport } from './routes/(hidden-folder)/layouts/visibleLayout/bar'
import { Route as hiddenFolderLayoutsHiddenLayoutFooImport } from './routes/(hidden-folder)/layouts/_hiddenLayout/foo'
import { Route as hiddenFolderLayoutsHiddenLayoutBarImport } from './routes/(hidden-folder)/layouts/_hiddenLayout/bar'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const hiddenFolderLayoutsImport = createFileRoute('/(hidden-folder)/layouts')()

// Create/Update Routes

const SearchingRoute = SearchingImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const Layout1Route = Layout1Import.update({
  id: '/_layout1',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const hiddenFolderLayoutsRoute = hiddenFolderLayoutsImport.update({
  id: '/(hidden-folder)/layouts',
  path: '/layouts',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIndexRoute = PokemonIndexImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRoute,
} as any)

const UserUsernameRoute = UserUsernameImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIdRoute = PokemonIdImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRoute,
} as any)

const hiddenFolderFirstLevelRoute = hiddenFolderFirstLevelImport.update({
  id: '/(hidden-folder)/first-level',
  path: '/first-level',
  getParentRoute: () => rootRoute,
} as any)

const Layout1UserRouteRoute = Layout1UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => Layout1Route,
} as any)

const OneTwoThreeRoute = OneTwoThreeImport.update({
  id: '/one/two/three',
  path: '/one/two/three',
  getParentRoute: () => rootRoute,
} as any)

const FooBarBazRoute = FooBarBazImport.update({
  id: '/foo/bar/baz',
  path: '/foo/bar/baz',
  getParentRoute: () => rootRoute,
} as any)

const hiddenFolderLayoutsVisibleLayoutRoute =
  hiddenFolderLayoutsVisibleLayoutImport.update({
    id: '/visibleLayout',
    path: '/visibleLayout',
    getParentRoute: () => hiddenFolderLayoutsRoute,
  } as any)

const hiddenFolderLayoutsHiddenLayoutRoute =
  hiddenFolderLayoutsHiddenLayoutImport.update({
    id: '/_hiddenLayout',
    getParentRoute: () => hiddenFolderLayoutsRoute,
  } as any)

const hiddenFolderLayoutsVisibleLayoutFooRoute =
  hiddenFolderLayoutsVisibleLayoutFooImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)

const hiddenFolderLayoutsVisibleLayoutBarRoute =
  hiddenFolderLayoutsVisibleLayoutBarImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)

const hiddenFolderLayoutsHiddenLayoutFooRoute =
  hiddenFolderLayoutsHiddenLayoutFooImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)

const hiddenFolderLayoutsHiddenLayoutBarRoute =
  hiddenFolderLayoutsHiddenLayoutBarImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout1': {
      id: '/_layout1'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Layout1Import
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingImport
      parentRoute: typeof rootRoute
    }
    '/_layout1/user': {
      id: '/_layout1/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof Layout1UserRouteImport
      parentRoute: typeof Layout1Import
    }
    '/(hidden-folder)/first-level': {
      id: '/(hidden-folder)/first-level'
      path: '/first-level'
      fullPath: '/first-level'
      preLoaderRoute: typeof hiddenFolderFirstLevelImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdImport
      parentRoute: typeof rootRoute
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonIndexImport
      parentRoute: typeof rootRoute
    }
    '/(hidden-folder)/layouts': {
      id: '/(hidden-folder)/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof hiddenFolderLayoutsImport
      parentRoute: typeof rootRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout': {
      id: '/(hidden-folder)/layouts/_hiddenLayout'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutImport
      parentRoute: typeof hiddenFolderLayoutsRoute
    }
    '/(hidden-folder)/layouts/visibleLayout': {
      id: '/(hidden-folder)/layouts/visibleLayout'
      path: '/visibleLayout'
      fullPath: '/layouts/visibleLayout'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutImport
      parentRoute: typeof hiddenFolderLayoutsImport
    }
    '/foo/bar/baz': {
      id: '/foo/bar/baz'
      path: '/foo/bar/baz'
      fullPath: '/foo/bar/baz'
      preLoaderRoute: typeof FooBarBazImport
      parentRoute: typeof rootRoute
    }
    '/one/two/three': {
      id: '/one/two/three'
      path: '/one/two/three'
      fullPath: '/one/two/three'
      preLoaderRoute: typeof OneTwoThreeImport
      parentRoute: typeof rootRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout/bar': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/bar'
      path: '/bar'
      fullPath: '/layouts/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutBarImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutImport
    }
    '/(hidden-folder)/layouts/_hiddenLayout/foo': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/foo'
      path: '/foo'
      fullPath: '/layouts/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutFooImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutImport
    }
    '/(hidden-folder)/layouts/visibleLayout/bar': {
      id: '/(hidden-folder)/layouts/visibleLayout/bar'
      path: '/bar'
      fullPath: '/layouts/visibleLayout/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutBarImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutImport
    }
    '/(hidden-folder)/layouts/visibleLayout/foo': {
      id: '/(hidden-folder)/layouts/visibleLayout/foo'
      path: '/foo'
      fullPath: '/layouts/visibleLayout/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutFooImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutImport
    }
  }
}

// Create and export the route tree

interface Layout1RouteChildren {
  Layout1UserRouteRoute: typeof Layout1UserRouteRoute
}

const Layout1RouteChildren: Layout1RouteChildren = {
  Layout1UserRouteRoute: Layout1UserRouteRoute,
}

const Layout1RouteWithChildren =
  Layout1Route._addFileChildren(Layout1RouteChildren)

interface hiddenFolderLayoutsHiddenLayoutRouteChildren {
  hiddenFolderLayoutsHiddenLayoutBarRoute: typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  hiddenFolderLayoutsHiddenLayoutFooRoute: typeof hiddenFolderLayoutsHiddenLayoutFooRoute
}

const hiddenFolderLayoutsHiddenLayoutRouteChildren: hiddenFolderLayoutsHiddenLayoutRouteChildren =
  {
    hiddenFolderLayoutsHiddenLayoutBarRoute:
      hiddenFolderLayoutsHiddenLayoutBarRoute,
    hiddenFolderLayoutsHiddenLayoutFooRoute:
      hiddenFolderLayoutsHiddenLayoutFooRoute,
  }

const hiddenFolderLayoutsHiddenLayoutRouteWithChildren =
  hiddenFolderLayoutsHiddenLayoutRoute._addFileChildren(
    hiddenFolderLayoutsHiddenLayoutRouteChildren,
  )

interface hiddenFolderLayoutsVisibleLayoutRouteChildren {
  hiddenFolderLayoutsVisibleLayoutBarRoute: typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  hiddenFolderLayoutsVisibleLayoutFooRoute: typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

const hiddenFolderLayoutsVisibleLayoutRouteChildren: hiddenFolderLayoutsVisibleLayoutRouteChildren =
  {
    hiddenFolderLayoutsVisibleLayoutBarRoute:
      hiddenFolderLayoutsVisibleLayoutBarRoute,
    hiddenFolderLayoutsVisibleLayoutFooRoute:
      hiddenFolderLayoutsVisibleLayoutFooRoute,
  }

const hiddenFolderLayoutsVisibleLayoutRouteWithChildren =
  hiddenFolderLayoutsVisibleLayoutRoute._addFileChildren(
    hiddenFolderLayoutsVisibleLayoutRouteChildren,
  )

interface hiddenFolderLayoutsRouteChildren {
  hiddenFolderLayoutsHiddenLayoutRoute: typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  hiddenFolderLayoutsVisibleLayoutRoute: typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
}

const hiddenFolderLayoutsRouteChildren: hiddenFolderLayoutsRouteChildren = {
  hiddenFolderLayoutsHiddenLayoutRoute:
    hiddenFolderLayoutsHiddenLayoutRouteWithChildren,
  hiddenFolderLayoutsVisibleLayoutRoute:
    hiddenFolderLayoutsVisibleLayoutRouteWithChildren,
}

const hiddenFolderLayoutsRouteWithChildren =
  hiddenFolderLayoutsRoute._addFileChildren(hiddenFolderLayoutsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof Layout1RouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/user': typeof Layout1UserRouteRoute
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/pokemon': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof Layout1RouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/user': typeof Layout1UserRouteRoute
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/pokemon': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_layout1': typeof Layout1RouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/_layout1/user': typeof Layout1UserRouteRoute
  '/(hidden-folder)/first-level': typeof hiddenFolderFirstLevelRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/(hidden-folder)/layouts': typeof hiddenFolderLayoutsRouteWithChildren
  '/(hidden-folder)/layouts/_hiddenLayout': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/(hidden-folder)/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/(hidden-folder)/layouts/_hiddenLayout/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/(hidden-folder)/layouts/_hiddenLayout/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/(hidden-folder)/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/(hidden-folder)/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/search'
    | '/searching'
    | '/user'
    | '/first-level'
    | '/pokemon/$id'
    | '/user/$username'
    | '/pokemon'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/search'
    | '/searching'
    | '/user'
    | '/first-level'
    | '/pokemon/$id'
    | '/user/$username'
    | '/pokemon'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  id:
    | '__root__'
    | '/'
    | '/_layout1'
    | '/about'
    | '/search'
    | '/searching'
    | '/_layout1/user'
    | '/(hidden-folder)/first-level'
    | '/pokemon/$id'
    | '/user/$username'
    | '/pokemon/'
    | '/(hidden-folder)/layouts'
    | '/(hidden-folder)/layouts/_hiddenLayout'
    | '/(hidden-folder)/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/(hidden-folder)/layouts/_hiddenLayout/bar'
    | '/(hidden-folder)/layouts/_hiddenLayout/foo'
    | '/(hidden-folder)/layouts/visibleLayout/bar'
    | '/(hidden-folder)/layouts/visibleLayout/foo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  Layout1Route: typeof Layout1RouteWithChildren
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  SearchingRoute: typeof SearchingRoute
  hiddenFolderFirstLevelRoute: typeof hiddenFolderFirstLevelRoute
  PokemonIdRoute: typeof PokemonIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  hiddenFolderLayoutsRoute: typeof hiddenFolderLayoutsRouteWithChildren
  FooBarBazRoute: typeof FooBarBazRoute
  OneTwoThreeRoute: typeof OneTwoThreeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  Layout1Route: Layout1RouteWithChildren,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  SearchingRoute: SearchingRoute,
  hiddenFolderFirstLevelRoute: hiddenFolderFirstLevelRoute,
  PokemonIdRoute: PokemonIdRoute,
  UserUsernameRoute: UserUsernameRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  hiddenFolderLayoutsRoute: hiddenFolderLayoutsRouteWithChildren,
  FooBarBazRoute: FooBarBazRoute,
  OneTwoThreeRoute: OneTwoThreeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout1",
        "/about",
        "/search",
        "/searching",
        "/(hidden-folder)/first-level",
        "/pokemon/$id",
        "/user/$username",
        "/pokemon/",
        "/(hidden-folder)/layouts",
        "/foo/bar/baz",
        "/one/two/three"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout1": {
      "filePath": "_layout1.tsx",
      "children": [
        "/_layout1/user"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/searching": {
      "filePath": "searching.tsx"
    },
    "/_layout1/user": {
      "filePath": "_layout1/user/route.tsx",
      "parent": "/_layout1"
    },
    "/(hidden-folder)/first-level": {
      "filePath": "(hidden-folder)/first-level.tsx"
    },
    "/pokemon/$id": {
      "filePath": "pokemon/$id.tsx"
    },
    "/user/$username": {
      "filePath": "user.$username.tsx"
    },
    "/pokemon/": {
      "filePath": "pokemon/index.tsx"
    },
    "/(hidden-folder)/layouts": {
      "filePath": "(hidden-folder)/layouts",
      "children": [
        "/(hidden-folder)/layouts/_hiddenLayout",
        "/(hidden-folder)/layouts/visibleLayout"
      ]
    },
    "/(hidden-folder)/layouts/_hiddenLayout": {
      "filePath": "(hidden-folder)/layouts/_hiddenLayout.tsx",
      "parent": "/(hidden-folder)/layouts",
      "children": [
        "/(hidden-folder)/layouts/_hiddenLayout/bar",
        "/(hidden-folder)/layouts/_hiddenLayout/foo"
      ]
    },
    "/(hidden-folder)/layouts/visibleLayout": {
      "filePath": "(hidden-folder)/layouts/visibleLayout.tsx",
      "parent": "/(hidden-folder)/layouts",
      "children": [
        "/(hidden-folder)/layouts/visibleLayout/bar",
        "/(hidden-folder)/layouts/visibleLayout/foo"
      ]
    },
    "/foo/bar/baz": {
      "filePath": "foo/bar/baz.tsx"
    },
    "/one/two/three": {
      "filePath": "one.two.three.tsx"
    },
    "/(hidden-folder)/layouts/_hiddenLayout/bar": {
      "filePath": "(hidden-folder)/layouts/_hiddenLayout/bar.tsx",
      "parent": "/(hidden-folder)/layouts/_hiddenLayout"
    },
    "/(hidden-folder)/layouts/_hiddenLayout/foo": {
      "filePath": "(hidden-folder)/layouts/_hiddenLayout/foo.tsx",
      "parent": "/(hidden-folder)/layouts/_hiddenLayout"
    },
    "/(hidden-folder)/layouts/visibleLayout/bar": {
      "filePath": "(hidden-folder)/layouts/visibleLayout/bar.tsx",
      "parent": "/(hidden-folder)/layouts/visibleLayout"
    },
    "/(hidden-folder)/layouts/visibleLayout/foo": {
      "filePath": "(hidden-folder)/layouts/visibleLayout/foo.tsx",
      "parent": "/(hidden-folder)/layouts/visibleLayout"
    }
  }
}
ROUTE_MANIFEST_END */
